apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "itc-prometheus-chart.fullname" . }}-config
    labels:
        app: {{ include "itc-prometheus-chart.fullname" . }}
data:
    prometheus.yml: |-
        global:
            scrape_interval: {{ .Values.globalConfig.scrapeInterval }}
        scrape_configs:
        {{- range .Values.scrapeConfigs }}
            - job_name: .jobName
              static_configs:
                - targets: ['{{ .target }}:{{ .port }}']
        {{- end -}}